In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/W1 2023:2024.csv')
print(data.head())

             Wave  SiteID        Date Weather      Time  Count
0  2023 W1 spring  ML0001  22/06/2023     Dry  06:00:00      0
1  2023 W1 spring  ML0001  22/06/2023     Dry  06:15:00      0
2  2023 W1 spring  ML0001  22/06/2023     Dry  06:30:00      0
3  2023 W1 spring  ML0001  22/06/2023     Dry  06:45:00      0
4  2023 W1 spring  ML0001  22/06/2023     Dry  07:00:00      0

In [3]:
data.tail()

                  Wave  SiteID        Date Weather      Time  Count
768763  2024 W1 spring  ML0209  13/06/2024     Dry  20:45:00     11
768764  2024 W1 spring  ML0209  13/06/2024     Dry  21:00:00      5
768765  2024 W1 spring  ML0209  13/06/2024     Dry  21:15:00      4
768766  2024 W1 spring  ML0209  13/06/2024     Dry  21:30:00      3
768767  2024 W1 spring  ML0209  13/06/2024     Dry  21:45:00     10

In [4]:
data.isnull()

         Wave  SiteID   Date  Weather   Time  Count
0       False   False  False    False  False  False
1       False   False  False    False  False  False
2       False   False  False    False  False  False
3       False   False  False    False  False  False
4       False   False  False    False  False  False
...       ...     ...    ...      ...    ...    ...
768763  False   False  False    False  False  False
768764  False   False  False    False  False  False
768765  False   False  False    False  False  False
768766  False   False  False    False  False  False
768767  False   False  False    False  False  False

[768768 rows x 6 columns]

In [5]:
data.isna().any()

Wave       False
SiteID     False
Date       False
Weather    False
Time       False
Count      False
dtype: bool

In [6]:
data.isna().sum()

Wave       0
SiteID     0
Date       0
Weather    0
Time       0
Count      0
dtype: int64

In [7]:
data.isna().any().sum()

np.int64(0)

In [12]:
data = data.drop_duplicates()

In [13]:
data.duplicated().sum()

np.int64(0)

In [14]:
data.to_csv('W1_2023_2024_clean.csv', index=False)